### ISSUE TITLE
Crash on hello world application

### ISSUE THREAD

**Issue by hdante** [JuliaLang/Gtk.jl#144]
#!/usr/bin/env julia

using Gtk.ShortNames
import Gtk.gtk_main, Gtk.gtk_quit

window = @Window("Hello world")
signal_connect(window, "destroy") do widget
        println("Destroy")
end
showall(window)
gtk_main()

$ ./hello 

signal (11): Falha de segmentação
strlen at /usr/bin/../lib/libc.so.6 (unknown line)
g_type_name at /home/hdante/.julia/v0.3/Gtk/src/GLib/gtype.jl:66
getindex at /home/hdante/.julia/v0.3/Gtk/src/GLib/gvalues.jl:147
anonymous at /home/hdante/.julia/v0.3/Gtk/src/GLib/signals.jl:79
jl_handle_stack_switch at /usr/bin/../lib/julia/libjulia.so (unknown line)
julia_trampoline at /usr/bin/../lib/julia/libjulia.so (unknown line)
unknown function (ip: 4199613)
__libc_start_main at /usr/bin/../lib/libc.so.6 (unknown line)
unknown function (ip: 4199667)
unknown function (ip: 0)
fish: Job 1, './hello ' terminated by signal SIGSEGV (Address boundary error)

$ ./hello 
ERROR: Invalid GValue type
 in wait at /usr/bin/../lib/julia/sys.so
 in g_siginterruptible at /home/hdante/.julia/v0.3/Gtk/src/GLib/signals.jl:218
 in GClosureMarshal at /home/hdante/.julia/v0.3/Gtk/src/GLib/signals.jl:50
 in g_siginterruptible at /home/hdante/.julia/v0.3/Gtk/src/GLib/signals.jl:198
 in GClosureMarshal at /home/hdante/.julia/v0.3/Gtk/src/GLib/signals.jl:50

**Comment by vtjnash** [comment]
what version (or SHA1) of Gtk.jl are you using?

**Comment by lobingera** [comment]
i get the same. See #145 for the revision.

**Comment by hdante** [comment]
hdante@dragonmount ~> julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.5 (2015-01-08 22:33 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-unknown-linux-gnu

julia> Pkg.status()
1 required packages:
 - Gtk                           0.8.0
8 additional packages:
 - BinDeps                       0.3.7
 - Cairo                         0.2.24
 - Color                         0.4.1
 - Compat                        0.2.12
 - FixedPointNumbers             0.0.6
 - Graphics                      0.1.0
 - SHA                           0.0.3
 - URIParser                     0.0.4

**Comment by hdante** [comment]
Any updates about this bug ?

**Comment by xserxses** [comment]
Any chances to fix it?

**Comment by hdante** [comment]
Is the project dead ?

**Comment by timholy** [comment]
Show some patience. There are such things as people having other priorities (e.g., busy improving julia in other domains), going on vacation, etc. :smile:

Alternatively, feel free to contribute fixes yourself.

**Comment by timholy** [comment]
You should also understand that it's hard to fix problems you can't replicate. It doesn't crash for me, and I suspect it doesn't crash for Jameson.

**Comment by lobingera** [comment]
Well, that it doesn't crash somewhere else is some kind of new information, what system are you runnning?

**Comment by vtjnash** [comment]
what version of glib / gtk do you have on your system?

**Comment by timholy** [comment]
@lobingera, I'm running Kubuntu 14.04.

@hdante, here's a hunch: does it work if you run in the REPL rather than a script?

**Comment by lobingera** [comment]
julia> Gtk.libgtk
"/usr/lib/x86_64-linux-gnu/libgtk-3.so"

julia> Gtk.libglib
"/lib/x86_64-linux-gnu/libglib-2.0.so.0"

**Comment by hdante** [comment]
Lazy bitch, I have showed patience by waiting for an answer for 40 days before asking if the project was dead. :-) Also, seeing that the Gtk 10 line hello world crashes is itself a zen experience. :-)

In signals.js:GClosureMarshal, moving the call to g_siginterruptible() to the line before retval = cb(params...) solves the problem here.

I can't help more than that, you'll need to come back from your vacation now. :-)

**Comment by vtjnash** [comment]
what version of glib do you have?

the change you suggest is reasonable. i hadn't initially expected these to be allocated on the stack, but I guess that's not too surprising.

my time for working on Gtk.jl is in direct competition for the time I can spend on Julia itself. That usually  has meant that I only have time for this when Julia is in a pre-release feature freeze. and since neither of them is my day-job, so usually need to wait until I have a vacation to contribute to either.

**Comment by jiahao** [comment]
@hdante "lazy bitch" is _not_ an acceptable term of address.

**Comment by timholy** [comment]
@hdante, I'm glad to see that you're actually making use of the code which you have been given for free. Keep up the good work!

**Comment by hdante** [comment]
glib 2.42.2-1

Why would the stack allocation be a problem ? The stack should have been preserved, given the closure, even when executing from a different task, right ? This looks like a code generation bug to me.

**Comment by ViralBShah** [comment]
@hdante The language you used above is not acceptable as per the Julia community standards. You are probably well aware about how open source works, and poor language (even if in jest) only makes contributors less motivated.

http://julialang.org/community/standards/

I urge you to revisit your comment above and update it.

**Comment by hdante** [comment]
done

**Comment by ViralBShah** [comment]
Thank you!

**Comment by timholy** [comment]
FWIW, between the smileys and the obvious "contribution activity" stats on @vtjnash's and my GitHub home pages, I assumed this was meant entirely in jest. So no harm done. But no doubt it's better to moderate oneself so there is no risk of misinterpretation---smileys only go so far in medium with such limited interpersonal communication.

**Comment by lobingera** [comment]
i'm a little bit lost here...

>In signals.js:GClosureMarshal, moving the call to g_siginterruptible() to the line before retval = cb(params...) solves the problem here.

afaics g_siginterruptible *is* in the line before retval starting a do block?

So could someone please clarify, what is the needed change?
