### ISSUE TITLE
support julia 0.4

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/Gtk.jl#148]
there have been lots of changes in 0.4 (misc syntax, tuple types, ccall/cfunction). Gtk.jl needs to suppport them.

**Comment by ViralBShah** [comment]
I was just playing around with Gtk in 0.4, and found the same issue.

**Comment by vtjnash** [comment]
closed by 1b08531d694b42e55daa68c340ce1f509f2e4ccb
