### ISSUE TITLE
Failing on 0.3 on mac

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/Gtk.jl#149]
I installed Pkg.add("Gtk"), which brought Homebrew and installed a bunch of stuff. I get:
````
julia> using Gtk
ERROR: error in method definition: function Base.bytestring must be explicitly imported to be extended
 in include at /Users/viral/Desktop/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Users/viral/Desktop/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Users/viral/Desktop/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Users/viral/Desktop/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading /Users/viral/.julia/v0.3/Gtk/src/GLib/GLib.jl, in expression starting on line 27
while loading /Users/viral/.julia/v0.3/Gtk/src/Gtk.jl, in expression starting on line 6
````

**Comment by vtjnash** [comment]
closed by 512915d9d457368dd44f65f02f820817812a4bf0. just need to tag a new version

**Comment by ViralBShah** [comment]
Should I tag the most recent commit?

**Comment by vtjnash** [comment]
if you can confirm this works on another machine (e.g. not mine, and preferably linux or windows since I only tested on mac), then yes

**Comment by ViralBShah** [comment]
Confirmed on mac:

````

**Comment by vtjnash** [comment]
somewhat related, the tag Cairo needs to be updated to get rid of that warning/error

**Comment by ViralBShah** [comment]
Module loads fine on linux as well. Tried on 32-bit. If you'd like me to do a one line test of some kind to actually draw something, I can try that too.

**Comment by ViralBShah** [comment]
Could you tag whenever you are ready?

**Comment by vtjnash** [comment]
there's `Pkg.test("Gtk")` which does a reasonable job at providing a sanity check

**Comment by vtjnash** [comment]
tagged in https://github.com/JuliaLang/METADATA.jl/commit/071bc0f8f1fa18192886a16108b4d5299c59563a
