### ISSUE TITLE
Gtk conflicts with an existing identifier

### ISSUE THREAD

**Issue by lobingera** [JuliaLang/Gtk.jl#150]
```
lobi@orange4:~/juliarepo$ ../julia/julia 
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.7 (2015-03-23 21:36 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-linux-gnu

julia> using Gtk
Warning: using Cairo.width in module Gtk conflicts with an existing identifier.
Warning: using Cairo.getgc in module Gtk conflicts with an existing identifier.
Warning: using Cairo.height in module Gtk conflicts with an existing identifier.

julia> 
```

and this later on seems to create problems using Winston with gtk...

**Comment by timholy** [comment]
Probably due to Graphics. Other packages have standardized on a construct [like this](https://github.com/JuliaLang/Tk.jl/blob/master/src/Tk.jl#L27-L31), you could submit a PR to change Gtk to match.

**Comment by lobingera** [comment]
I guessed, that something like this is the problem. But i thought this non-definiton of re-defined functions is only effective in 0.4. However, doing things differently based on versions, doesn't look like elegant code.

**Comment by timholy** [comment]
If you think that, you'll simply hate Compat.jl. In a young language that changes syntax, etc, what's the alternative?

**Comment by timholy** [comment]
(Though to be fair, you find similar constructs all over the place in C code, too.)

**Comment by vtjnash** [comment]
This is a bug in Cairo (already fixed, but there needs to be a new version tagged)

**Comment by lobingera** [comment]
@timholy 
Well, i don't hate Compat.jl, i just don't really understand the julia way of manual dependency resolution...

**Comment by lobingera** [comment]
@vtjnash:
Could you please reference the issue in Cairo? From here it looks like it's not in master.

**Comment by timholy** [comment]
The whole remove-Graphics-from-Base thing was rough. Basically it's just that one needs to get one's Graphics module from a consistent place, but on 0.3 that only happens if everyone either always chooses Base.Graphics or always chooses the Graphics package. Maybe we should make the Graphics package uninstallable on 0.3?

**Comment by vtjnash** [comment]
I didn't look up an issue number other than to do a git pull on Cairo.jl so the issue seemed to go away

**Comment by slangangular** [comment]
@vtjnash:
I sill see the warning in Julia 0.3 with the latest versions of Gtk and Cairo. I did a ``Pkg.checkout()`` on both packages to get the latest version. Am I doing something wrong here?

````
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.8 (2015-04-30 23:40 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-unknown-linux-gnu

julia> Pkg.status()
4 required packages:
 - Distributions                 0.7.3
 - Gtk                           0.8.1              master
 - Optim                         0.4.1
 - Winston                       0.11.11            master
16 additional packages:
 - ArrayViews                    0.6.2
 - BinDeps                       0.3.12
 - Cairo                         0.2.27             master
 - Calculus                      0.1.8
 - Color                         0.4.5
 - Compat                        0.4.4
 - DualNumbers                   0.1.3
 - FixedPointNumbers             0.0.7
 - Graphics                      0.1.0
 - IniFile                       0.2.4
 - NaNMath                       0.0.2
 - PDMats                        0.3.3
 - SHA                           0.0.4
 - StatsBase                     0.6.15
 - Tk                            0.3.3
 - URIParser                     0.0.5

julia> using Gtk
Warning: using Cairo.width in module Gtk conflicts with an existing identifier.
Warning: using Cairo.getgc in module Gtk conflicts with an existing identifier.
Warning: using Cairo.height in module Gtk conflicts with an existing identifier.

**Comment by lobingera** [comment]
@slangangular 
I'm not sure, but this seems to be interference between Gtk, Cairo and Graphics and is vanishing with a recent v0.4.0 but then has other problems.

**Comment by slangangular** [comment]
Okay. In case you want to maintain compatibility with v0.3, I also included a fix for the tests, which were now failing. However the the tests still fail for me due to #145 (which is unrelated I believe).
