### ISSUE TITLE
Winston display not working anymore 

### ISSUE THREAD

**Issue by tknopp** [JuliaLang/Gtk.jl#154]
@vtjnash: Currently it seems not possible to render a Winston plot onto a Canvas. The following test example:

https://gist.github.com/tknopp/ae56b0509a0a4b80cfe1

does not work anymore. The plot is not shown and on the console it is written "warning: sub-optimal solution for plot". Thoughts?

**Comment by lobingera** [comment]
From the title i'd rather see this a Winston issue. Did you try to paint something into a Canvas without Winston. I usually try the Canvas example from the README.md (frontpage).

**Comment by lobingera** [comment]
btw: before my trouble with using Gtk started (~ v0.8.0) i had this behaviour: Canvas widget setup and mapped, but not drawing possible (i decided to update, then).
