### ISSUE TITLE
How to draw on canvas using Cairo and GTK in Julia

### ISSUE THREAD

**Issue by bobkhooke** [JuliaLang/Gtk.jl#156]
I'm trying to use Julia with GTK and Cairo to draw onto a canvas. I think the following code (adapted from the example fragments on the GTK.jl page) should work, but it does not. (Other GTK widgets work, but not the canvas)

I would appreciate if someone can suggest what is wrong with this code, or give a pointer to a complete example. 

The window appears with a solid gray background. No drawing commands (e.g. rectangle) work. There is no error message. This suggests the possibility that I need to somehow enable the visibility of the canvas, but I've tried various methods of doing that with no luck.

    using Gtk.ShortNames
    using Cairo
    
    function drawfn(w)
        ctx = Gtk.getgc(w)
        Cairo.set_coords(ctx, 0, 0, 800, 600, 0, 800, 0, 600)
        h = Gtk.height(w)
        w = Gtk.width(w)
    
        Gtk.rectangle(ctx, 0, 0, w/2, h/2)
        Gtk.set_source_rgb(ctx, 0, 0, 1)
        Gtk.fill(ctx)
    end
    
    
    function main()
    
        win = Gtk.@Window("stuff", 800,600)
        c = Gtk.@Canvas()
        Gtk.push!(win,c)
    
        Gtk.draw(drawfn, c)
        Gtk.showall(win)
    
    end
    
    main()

**Comment by vtjnash** [comment]
are you on Gtk.jl master or the latest release? I need to tag a new release version due a regression in the ability to draw on a Canvas.

**Comment by bobkhooke** [comment]
I'm running Julia Version 0.3.10-pre+4 (2015-06-04 13:19 UTC) Commit c8804e8 on 64bit linux.
The packages have versions:

 - Gtk                           0.8.1
 - Cairo                         0.2.27
 - Graphics                      0.1.0

**Comment by vtjnash** [comment]
i've just tagged v0.8.2, see if that helps

**Comment by bobkhooke** [comment]
That fixed it! That is wonderful! Thank you!
