### ISSUE TITLE
event handlers in canvas slow

### ISSUE THREAD

**Issue by lobingera** [JuliaLang/Gtk.jl#158]
I'm trying to do smooth animation (t < 1/20s) and i think i see a side effect of the installed event handlers in the canvas.

My code calls draw(canvas) on a regular basis (via Timer) and this works quite well. However when the mouse pointer is moved into the window, suddenly the updating stops. Like the handling of events (enter and move) stops further processing.

**Comment by lobingera** [comment]
needs better description and maybe profiling

**Comment by lobingera** [comment]
@vtjnash 
So you agree on this, or do you want to see the program and output?

**Comment by vtjnash** [comment]
if you have a simple program for testing / profiling this, that would be helpful. otherwise, the description sounded clear enough that I should be able to reproduce it.

**Comment by lobingera** [comment]
https://gist.github.com/lobingera/712c886cc75ca6019e49

I run this (see comand line) and when i move the mouse into the frame.
btw: this is a ubuntu 14.04 linux box and a recent v0.4

**Comment by lobingera** [comment]
@vtjnash 
Any update?

**Comment by lobingera** [comment]
i just updated to 0.4.0-dev+6526, this is even more emphasized.

**Comment by timholy** [comment]
I can reproduce. That's a useful test case. Interestingly, if I try my favorite trick, calling `@profile sleep(1)` (which usually lets me figure out where the bottleneck is) I just get a hang.

**Comment by vtjnash** [comment]
Thanks for bumping this again. Is was a busy month. I have a good handle on why it happens an I'm working on the fix to rate limit Gtk better.

**Comment by lobingera** [comment]
No hurry. What do you mean with 'rate limit'?

**Comment by vtjnash** [comment]
That's a good trick. If you are on Linux, you can also send SIGUSR1 (SIGINFO OR control-t on BSD/Apple)

**Comment by vtjnash** [comment]
btw. the demo program for this was awesome, it made fixing this really fun.

**Comment by timholy** [comment]
Nice!

**Comment by lobingera** [comment]
I was wandering to contribute this to something, but you need both Gtk and Cairo.

**Comment by timholy** [comment]
You could start a GtkDemos package?

**Comment by timholy** [comment]
(It is indeed a nice animation!)
