### ISSUE TITLE
Weird stock icons on OSX

### ISSUE THREAD

**Issue by timholy** [JuliaLang/Gtk.jl#184]
Compare linux:
https://github.com/JuliaGraphics/Immerse.jl/blob/master/images/zoom_hexbin_snapshot.png

vs OSX:
https://github.com/JuliaGraphics/Immerse.jl/issues/11#issuecomment-142383551

Users have commented that the OSX icons are non-intuitive.

**Comment by timholy** [comment]
CC @staticfloat, in case there's some extra package(?) that can be installed to fix this.

**Comment by vtjnash** [comment]
I think `gnome-icon-theme` may still need to be added to the homebrew gtk formula? The latest updates seem to only have included the "hicolor-icon-theme" fallback icons https://github.com/staticfloat/homebrew-juliadeps/pull/73/files#diff-25a65be87c71bc4f78331e6b8ca21d83R26

**Comment by staticfloat** [comment]
Mainline Homebrew [only includes `hicolor-icon-theme`](https://github.com/Homebrew/homebrew/blob/3d79800a6c90fdcfb9cb0ae1784cd01fe54501ca/Library/Formula/gtk%2B3.rb#L25), which was the lead I followed, but after doing some testing, it appears that the icons shown in the link above are the `gnome-icon-theme` icons.  `hicolor-icon-theme` by itself doesn't contain the icons we're interested in.  Perhaps we should install some other `gtk` theme?

**Comment by vtjnash** [comment]
i guess the icons are technically not part of gtk, but part of a theme or usage of it (with hicolor available as the generic fallback). the primary / default user is `gnome`, so on ubuntu (and probably other linux), the toplevel package would be `gnome-core` (or just `gnome`). but other windows managers might want to choose a different default theme, so `adwaita` isn't installed by default but instead is supposed to be selected by the application.

**Comment by staticfloat** [comment]
`adwaita-icon-theme` exists in Homebrew; let me try it out.

**Comment by staticfloat** [comment]
Well, darn, it's an alias for `gnome-icon-theme`.

**Comment by vtjnash** [comment]
yes, it seems the default `gnome-icon-theme` became `adwaita` about a year ago (https://blogs.gnome.org/mclasen/2014/06/13/a-new-default-theme-for-gtk/)

**Comment by timholy** [comment]
I'm guessing the best option is to do nothing, then?

**Comment by staticfloat** [comment]
Yeah, I think so.  Not much we can do here except choose icons that look good on both platforms.
