### ISSUE TITLE
Segfault on save-as dialog from toolbar icon

### ISSUE THREAD

**Issue by timholy** [JuliaLang/Gtk.jl#185]
This is continuing the investigations in https://github.com/JuliaGraphics/Immerse.jl/issues/13.

@pagnani, do any of the other toolbar icons in Immerse work for you?

Also, does this work to bring up the save-as dialog when you click on the button?
```
using Gtk.ShortNames
win = @Window("test") |> (btn = @Button("Save as")) |> showall
signal_connect(btn, "clicked") do widget
    save_dialog("Save as...")
end
```
By "work" I mean no segfaults :smile:.

If that works, how about
```
win = @Window("test") |> ((tb = @Toolbar()) |> (tb1 = @ToolButton("gtk-save-as"))) |> showall
signal_connect(tb1, "clicked") do widget
    save_dialog("Save as...")
end
```

**Comment by pagnani** [comment]
Immerse window

0) Save as: crashes
1) Zoom is ok
2) 1:1 (which in my case looks like a bold 1 like an indicator function if you know what I mean) is ok
3) lasso selection : seems to work ok but  once has crashed (not reproducible tough) when I typed in the REPL the variable `selection`. 

Test 1

No save-as-dialog (but no crash either) but only a windows with "save as" written on the center.

Test 2

There is the ugly icon below:
<img width="749" alt="screen shot 2015-09-24 at 1 01 02 pm" src="https://cloud.githubusercontent.com/assets/1280414/10072461/25e2c382-62c2-11e5-8354-46aa4bb10938.png">

but no dialog popping out, and no crash

**Comment by pagnani** [comment]
sorry this screenshot not the previous one
<img width="202" alt="screen shot 2015-09-24 at 1 42 36 pm" src="https://cloud.githubusercontent.com/assets/1280414/10072479/50f4a23e-62c2-11e5-943a-af2deee1760e.png">

**Comment by timholy** [comment]
OK, let's see if it's similar to https://github.com/JuliaLang/Gtk.jl/issues/161: can you try
```jl
win = @Window("test") |> (btn = @Button("Save as")) |> showall
function saveas_cb(::Ptr, user_data)
    save_dialog("Save as...")
    nothing
end
signal_connect(saveas_cb, btn, "clicked", Void, ())
```

**Comment by pagnani** [comment]
That is working: a working dialog is now popping out. There is only a message on the REPL
```
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```

**Comment by timholy** [comment]
That warning is just a consequence of how I tested this, and shouldn't be an issue when I work around this in Immerse. (If it is, please do report it as an issue.)

I now know how to work around this. Thanks for all your patience and help in working through this!

Since it's basically a dup of #161, I'll close this.

**Comment by pagnani** [comment]
Glad to help!
