### ISSUE TITLE
Recompiling Cairo BoundsError when precompiling Gtk

### ISSUE THREAD

**Issue by UrbanKristan** [JuliaLang/Gtk.jl#202]
Running "using Gtk" gives me the following traceback:

INFO: Precompiling module Gtk...
INFO: Recompiling stale cache file C:\Users\Urban\.julia\lib\v0.4\Cairo.ji for m
odule Cairo.
ERROR: LoadError: BoundsError: attempt to access 157-element Array{Any,1}:
   Symbol
   Int8
   UInt8
   Int16
   UInt16
   Int32
   UInt32
   Int64
   UInt64
   Int128
  ?
 24
 25
 26
 27
 28
 29
 30
 31
 32
  at index [-1]
while loading C:\Users\Urban\.julia\v0.4\Gtk\src\Gtk.jl, in expression starting
on line 66
ERROR: Failed to precompile Gtk to C:\Users\Urban\.julia\lib\v0.4\Gtk.ji
 in error at error.jl:21
 in compilecache at loading.jl:383
 in require at loading.jl:250

**Comment by timholy** [comment]
What does `Pkg.status("Gtk")` say? I'm trying to match up that line number against the current source, and [it doesn't seem to make sense](https://github.com/JuliaLang/Gtk.jl/blob/cdf923ad773c4dd30339775e530e04f657d7dbd4/src/Gtk.jl#L66).

**Comment by UrbanKristan** [comment]
It says:
 - Gtk                           0.9.3+             master

**Comment by UrbanKristan** [comment]
My Gtk.jl file is the same as the one in your link

**Comment by UrbanKristan** [comment]
Turns out I was using an old version of Julia. Sorry.

**Comment by timholy** [comment]
No problem, glad you figured it out.
