### ISSUE TITLE
path_at_pos problem

### ISSUE THREAD

**Issue by lucianolorenti** [JuliaLang/Gtk.jl#218]
I'm having trouble with the function path_at_pos
`function path_at_pos(treeView::GtkTreeView, x::Integer, y::Integer)`

for some reason this lines fails
`path = convert(Gtk.GtkTreePath,pathPtr[])`

pathPtr is defined as 
`pathPtr = Gtk.mutable(Ptr{Gtk.GtkTreePath})`

The error message is:

> ERROR: MethodError: `convert` has no method matching convert(::Type{Ptr{Gtk.GtkTreePath}}, ::Void)
> This may have arisen from a call to the constructor Ptr{Gtk.GtkTreePath}(...),
> since type constructors fall back to convert methods.
> Closest candidates are:
>   call{T}(::Type{T}, ::Any)
>   convert{T}(::Type{Ptr{T}}, ::UInt64)
>   convert{T}(::Type{Ptr{T}}, ::Int64)
>   ...
> ERROR (unhandled task failure): MethodError: `convert` has no method matching convert(::Type{Ptr{Gtk.GtkTreePath}}, ::Void)
> This may have arisen from a call to the constructor Ptr{Gtk.GtkTreePath}(...),
> since type constructors fall back to convert methods.
> Closest candidates are:
>   call{T}(::Type{T}, ::Any)
>   convert{T}(::Type{Ptr{T}}, ::UInt64)
>   convert{T}(::Type{Ptr{T}}, ::Int64)
>   ...
> 
>

**Comment by lucianolorenti** [comment]
This an example of what i am talking about. I copied the path_at_pos function into this code. I am not sure why isn't working. I've tried some workarounds but I couldn't make it works.
```
using Gtk

function _path_at_pos(treeView::GtkTreeView, x::Integer, y::Integer)
    pathPtr = Gtk.mutable(Ptr{Gtk.GtkTreePath})
    path = Gtk.GtkTreePath()

    ret = ccall((:gtk_tree_view_get_path_at_pos,Gtk.libgtk),Cint,
                      (Ptr{GObject},Cint,Cint,Ptr{Ptr{Void}},Ptr{Ptr{Void}},Ptr{Cint},Ptr{Cint} ),
                       treeView,x,y,pathPtr,C_NULL,C_NULL,C_NULL) != 0
    if ret
      path = convert(Gtk.GtkTreePath, pathPtr[])
    end
    ret, path
end 

function filespanel_treeview_clicked_cb(widgetptr::Ptr, eventptr::Ptr, user_data)
    treeview = convert(GtkTreeView, widgetptr)
    event = convert(Gtk.GdkEvent, eventptr)
    x = round(Int,event.x)
    y = round(Int,event.y)
    (ret,path) = _path_at_pos(treeview,x,y);
    return nothing
end

function give_me_a_treeview(n,rownames)

    t = ntuple(i->AbstractString,n)
    list = @GtkTreeStore(t...)

    tv = @GtkTreeView(GtkTreeModel(list))

    cols = Array(GtkTreeViewColumn,0)

    for i=1:n
        r1 = @GtkCellRendererText()
        c1 = @GtkTreeViewColumn(rownames[i], r1, Dict([("text",i-1)]))
        Gtk.G_.sort_column_id(c1,i-1)
        push!(cols,c1)
        Gtk.G_.max_width(c1,Int(200/n))
        push!(tv,c1)
    end

    return (tv,list,cols)
end

(tv,list,cols) = give_me_a_treeview(2,["test","test1"]);
        signal_connect(filespanel_treeview_clicked_cb,tv, "button-press-event",
        Void, (Ptr{Gtk.GdkEvent},))
for i =1:10
   push!(list,("aaa","bb"))
end
w = Gtk.@Window("hello");
push!(w,tv);
showall(w)
```

**Comment by jonathanBieler** [comment]
I don't really understand all these pointers and conversion, but if you do 

    path = unsafe_load(unsafe_load(pathPtr))

It seems to work (pathPtr is a pointer to a pointer that point on a GtkTreePath, so  unsafe_load(pathPtr) is a pointer to a GtkTreePath).

Note also that you can add `@guarded (nothing) ` in front of your callback, to prevent it crashing everything when there's a error in the callback.

**Comment by lucianolorenti** [comment]
Yes. I didn't understand it either. 

> function path_at_pos(treeView::GtkTreeView, x::Integer, y::Integer)
is defined in lists.jl in the line 679. 
I suppose I can make a pull request.

**Comment by lucianolorenti** [comment]
I make it work with:

```
function path_at_pos(treeView::GtkTreeView, x::Integer, y::Integer)
    pathPtr = Ref{Ptr{GtkTreePath}}(0)

    ret = ccall((:gtk_tree_view_get_path_at_pos,libgtk),Cint,
                      (Ptr{GObject},Cint,Cint,Ref{Ptr{GtkTreePath}},Ptr{Ptr{Void}},Ptr{Cint},Ptr{Cint} ),
                       treeView,x,y,pathPtr,C_NULL,C_NULL,C_NULL) != 0
    if ret
        path = GtkTreePath(pathPtr[],true)
    else
      path = GtkTreePath()
    end
    ret, path
end
```
