### ISSUE TITLE
Gtk fails to parse on master.

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Gtk.jl#226]
The problem is that this syntax https://github.com/JuliaLang/Gtk.jl/blob/e6b8e49ed76b8fc92e7e3ff5781fec91b8102cc2/src/events.jl#L146 is now a parser error.

Is this statement even expressible in the 0.5 syntax rules?

One way to fix it is just to drop support for 0.3.

**Comment by yuyichao** [comment]
> Is this statement even expressible in the 0.5 syntax rules?

`@compat`

**Comment by KristofferC** [comment]
This is not in compat right now, right? I could try add it.

**Comment by yuyichao** [comment]
What I mean is you can write

```
@compat typealias MHPair Tuple{MouseHandler,Symbol}
```

Or maybe even

```jl
typealias MHPair tuple(MouseHandler,Symbol)
```

or

```jl
const MHPair = (MouseHandler,Symbol)
```

**Comment by KristofferC** [comment]
Ok, I saw it now that it existed Compat.
