### ISSUE TITLE
How to update the progress bar on a GUI

### ISSUE THREAD

**Issue by tddaniel** [JuliaLang/Gtk.jl#230]
I am new to Gtk so sorry if this has an obvious answer. I am trying to get a progress bar to 
update while a callback is running, but the window is frozen after the button is pressed and the callback runs. I have read some about using different processes ( issue #57)  with `addprocs()` but I can't seem to get that correct. (I am new to parallel computing too,  hurrah for new things! ). Below is the toy example I am starting from (where the window freezes until the callback is done). Any help would be appreciated. 
```
using Gtk


function make_window()
  win = @GtkWindow()
  g = @GtkGrid()
  btn = @GtkButton("Start")
  p = @GtkProgressBar()
  g[1,5] = btn
  g[1:3, 8] = p
  push!(win, g)
  showall(win)
  return win, btn, p
end

function callback(widget)
  print("it lives!")
  for i in 1:20
    sleep(0.5)
    setproperty!(p, :fraction, i/20)
  end
end


win, btn, p =  make_window()
  id = signal_connect(callback, btn, "clicked")
```

**Comment by lucianolorenti** [comment]
try this:

```

function make_window()
  win = @GtkWindow()
  g = @GtkGrid()
  btn = @GtkButton("Start")
  p = @GtkProgressBar()
  g[1,5] = btn
  g[1:3, 8] = p
  push!(win, g)
  showall(win)
  return win, btn, p
end

function callback(widget)
  print("it lives!")
  @schedule begin 
      for i in 1:20
        sleep(0.5)
       setproperty!(p, :fraction, i/20)
     end
   end
end


win, btn, p =  make_window()
id = signal_connect(callback, btn, "clicked")
```

**Comment by tddaniel** [comment]
That works. Thanks so much, I (sadly) spent all afternoon on that. The `@schedule` is creating a separate thread for the loop to run in, is that correct?
